FROM java:8

VOLUME /tmp

ADD backend-service-0.0.1-SNAPSHOT.jar /backend-service-0.0.1-SNAPSHOT.jar

RUN sh -c 'touch /backend-service-0.0.1-SNAPSHOT.jar'

ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /backend-service-0.0.1-SNAPSHOT.jar" ]


#####################################################
#	docker build -t backendService .
#	docker run -d --net=host --name=backendSrvice -p 8080:8080  backend-service
#
####################################################